### ISSUE TITLE
Incomplete filters with new ITKv5 multithreading

### ISSUE THREAD

**Issue by mseng10** [InsightSoftwareConsortium/ITKLabelErodeDilate#27]
I am in the process of configuring all remote modules to pass ci-testing. When configured with `ITK_LEGACY_REMOVE= ON`, many of the tests are failing due to the following error: 

` itk::ExceptionObject (0x7fab29007fc0)
2662: Location: "virtual void itk::ImageSource<itk::Image<unsigned char, 3> >::ThreadedGenerateData(const itk::ImageSource::OutputImageRegionType &, itk::ThreadIdType) [TOutputImage = itk::Image<unsigned char, 3>]" 
2662: File: /Users/mseng/ITK/Modules/Core/Common/include/itkImageSource.hxx
2662: Line: 262
2662: Description: itk::ERROR: itk::ERROR: LabelSetErodeImageFilter(0x7fab290059e0): With DynamicMultiThreadingOff subclass should override this method. The signature of ThreadedGenerateData() has been changed in ITK v4 to use the new ThreadIdType.`

The filter class primarily used for this module is `itkLabelSetMorphBaseImageFilter`. In recent commits, this was updated to utilize the new Multithreading system used in ITK. These changes included:

- Changing `ThreadedGenerateData` to `DynamicThreadedGenerateData` and removing parameter `theadID`
- Updated `MultiThreaderBase` variables
- Setting `this->DynamicMultiThreadingOn();` in filter's constructor

All of these changes are in line with the ITKv5 migration guide. However, this filter utilizes a  customer region splitting function that requires the use of the classic multi-threader. In order for this module to pass tests, I believe the module has to be reverted back to its original state. The case is the same for remote module `ParabolicMorphology`, but I am unable to create an issue for that repository. Any information regarding this issue would be appreciated.

**Comment by thewtex** [comment]
@dzenanz

**Comment by dzenanz** [comment]
When there is some reason to use the classic multi-threading (such as custom region splitter), call `this->DynamicMultiThreadingOff();` in filter's constructor and keep the existing threading signatures.

**Comment by mseng10** [comment]
@dzenanz Thank you!

**Comment by richardbeare** [comment]
@dzenanz @mseng10 @thewtex 

A similar problem is likely in the parabolic morphology module. Have received a bug report for a package using that module: https://github.com/DevelopmentalImagingMCRI/mantis/issues/10#issuecomment-623097280

**Comment by mseng10** [comment]
@richardbeare There is a pending PR for ParabolicMorphology that addresses this issue. Here is the [Link](https://github.com/InsightSoftwareConsortium/ITKParabolicMorphology/pull/28)!

**Comment by richardbeare** [comment]
I should add that the threading approach in these filters was very similar to the RecursiveGaussian family of filters. If that family adopted something special in the 5.1 upgrade then we should think about doing the same for the parabolic family. Note that I haven't checked whether anything special was done.
