### ISSUE TITLE
ITKLabelErodeDilate not compatible with itk==5.3.0

### ISSUE THREAD

**Issue by dyollb** [InsightSoftwareConsortium/ITKLabelErodeDilate#37]
It would be great if this remote module were available for recent versions of ITK.
The latest release it is not compatible with ITK 5.3.0

![image](https://user-images.githubusercontent.com/12702862/218405537-013e0f4f-3af1-446c-b4f4-247929b3a9da.png)

**Comment by dzenanz** [comment]
Fixed by #38.

**Comment by dzenanz** [comment]
Packages are now available:
https://pypi.org/project/itk-labelerodedilate/1.2.1/

Can you confirm that this now works?

**Comment by dyollb** [comment]
> Packages are now available: https://pypi.org/project/itk-labelerodedilate/1.2.1/
> 
> Can you confirm that this now works?

I can confirm. It works! Thanks @dzenanz
